package com.model.takeout;
// Generated 2015-9-18 16:25:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.model.Model;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food", catalog = "takeout")
public class Food extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = -5099353823771326577L;
	private String description;
	private Integer id;
	private String image;
	private String name;
	private double price;

	public Food() {
	}

	public Food(String name, double price, String description, String image) {
		this.name = name;
		this.price = price;
		this.description = description;
		this.image = image;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "image", length = 100)
	public String getImage() {
		return this.image;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	@Column(name = "price", precision = 10)
	public double getPrice() {
		return this.price;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Override
	public String toString() {
		return "食品名称" + name;
	}

}
