package com.model.takeout;
// Generated 2015-9-23 15:39:14 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.model.Model;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "takeout")
public class Image extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = 5495042522586296968L;
	private Food food;
	private Integer id;
	private String url;

	public Image() {
	}

	public Image(Food food, String url) {
		this.food = food;
		this.url = url;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fid", nullable = false)
	public Food getFood() {
		return this.food;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "url", nullable = false, length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
