package com.model.takeout;
// Generated 2015-9-23 15:39:14 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.model.Model;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "takeout")
public class Image extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = 5495042522586296968L;
	private Date date;
	private Food food;
	private long id;
	private String name;
	private String url;

	public Image() {
	}

	public Image(Food food, String url, String name, Date date) {
		this.food = food;
		this.url = url;
		this.name = name;
		this.date = date;
	}

	@Column(name = "date", nullable = false)
	public Date getDate() {
		return date;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fid", nullable = false)
	public Food getFood() {
		return this.food;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return name;
	}

	@Column(name = "url", nullable = false, length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
