package com.model.takeout;
// Generated 2015-9-18 16:25:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.model.Model;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "takeout")
public class Menu extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = -5347038657584722962L;
	private List<Menu> children = new ArrayList<Menu>();
	private boolean display;
	private String icon;
	private Integer id;
	private boolean leaf;
	private String name;
	private Integer ordercol;
	private Menu parent;
	private String text;

	@Enumerated(EnumType.STRING)
	private MenuType type;
	private String url;

	public Menu() {
	}

	public Menu(boolean display, boolean leaf) {
		this.display = display;
		this.leaf = leaf;
	}

	public Menu(Menu parent, String icon, boolean display, boolean leaf, String name, String text, MenuType type,
			String url, Integer ordercol, List<Menu> children) {
		this.parent = parent;
		this.icon = icon;
		this.display = display;
		this.leaf = leaf;
		this.name = name;
		this.text = text;
		this.type = type;
		this.url = url;
		this.ordercol = ordercol;
		this.children = children;
	}

	@OneToMany(mappedBy = "parent")
	public List<Menu> getChildren() {
		return this.children;
	}

	@Column(name = "display", nullable = false)
	public boolean getDisplay() {
		return this.display;
	}

	@Column(name = "icon")
	public String getIcon() {
		return this.icon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "leaf", nullable = false)
	public boolean getLeaf() {
		return this.leaf;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	@Column(name = "ordercol")
	public Integer getOrdercol() {
		return this.ordercol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Menu getParent() {
		return this.parent;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public MenuType getType() {
		return this.type;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}

	public void setDisplay(boolean display) {
		this.display = display;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setLeaf(boolean leaf) {
		this.leaf = leaf;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setOrdercol(Integer ordercol) {
		this.ordercol = ordercol;
	}

	public void setParent(Menu parent) {
		this.parent = parent;
	}

	public void setText(String text) {
		this.text = text;
	}

	public void setType(MenuType type) {
		this.type = type;
	}

	public void setType(String typeString) {
		if (typeString.equals("node")) {
			this.type = MenuType.NODE;
		} else if (typeString.equals("category")) {
			this.type = MenuType.CATEGORY;
		} else if (typeString.equals("root")) {
			this.type = MenuType.ROOT;
		}
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
