package com.model.takeout;
// Generated 2015-9-23 15:39:14 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.model.Model;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "takeout")
public class Menu extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = 1777194429567102177L;
	private List<Menu> children = new ArrayList<Menu>();
	private boolean display;
	private String icon;
	private Integer id;
	private boolean leaf;
	private String name;
	private Integer ordercol;
	private Menu parent;
	private String text;
	private String type;
	private String url;

	public Menu() {
	}

	public Menu(boolean leaf) {
		this.leaf = leaf;
	}

	public Menu(Menu parent, boolean display, String icon, boolean leaf, String name, Integer ordercol, String text,
			String type, String url, List<Menu> children) {
		this.parent = parent;
		this.display = display;
		this.icon = icon;
		this.leaf = leaf;
		this.name = name;
		this.ordercol = ordercol;
		this.text = text;
		this.type = type;
		this.url = url;
		this.children = children;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public List<Menu> getChildren() {
		return this.children;
	}

	@Column(name = "display")
	public boolean getDisplay() {
		return this.display;
	}

	@Column(name = "icon", length = 45)
	public String getIcon() {
		return this.icon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "leaf", nullable = false)
	public boolean getLeaf() {
		return this.leaf;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	@Column(name = "ordercol")
	public Integer getOrdercol() {
		return this.ordercol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Menu getParent() {
		return this.parent;
	}

	@Column(name = "text", length = 45)
	public String getText() {
		return this.text;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}

	public void setDisplay(boolean display) {
		this.display = display;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setLeaf(boolean leaf) {
		this.leaf = leaf;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setOrdercol(Integer ordercol) {
		this.ordercol = ordercol;
	}

	public void setParent(Menu parent) {
		this.parent = parent;
	}

	public void setText(String text) {
		this.text = text;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
