package com.model.takeout;
// Generated 2015-9-18 16:25:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.model.Model;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "takeout")
public class Order extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = -3250014297111213677L;
	private String address;
	private String content;
	private Date createtime;
	private Integer id;
	private Integer payStatus;
	private String phoneNumber;
	private double sum;
	private Integer uid;
	private String username;

	public Order() {
	}

	public Order(Date createtime, String content, double sum, Integer uid, String username, String phoneNumber,
			String address, Integer payStatus) {
		this.createtime = createtime;
		this.content = content;
		this.sum = sum;
		this.uid = uid;
		this.username = username;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.payStatus = payStatus;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "payStatus")
	public Integer getPayStatus() {
		return this.payStatus;
	}

	@Column(name = "phoneNumber", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	@Column(name = "sum", precision = 10)
	public double getSum() {
		return this.sum;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public void setSum(double sum) {
		this.sum = sum;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
