package com.model.takeout;
// Generated 2015-9-23 15:39:14 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.model.Model;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "takeout")
public class Order extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = 3968813071718506723L;
	private String address;
	private Date createtime;
	private List<Food> foods = new ArrayList<Food>();
	private int id;
	private Integer payStatus;
	private String phoneNumber;
	private double sum;
	private User user;
	private String username;

	public Order() {
	}

	public Order(int id) {
		this.id = id;
	}

	public Order(int id, User user) {
		this.id = id;
		this.user = user;
	}

	public Order(User user, String address, Date createtime, Integer payStatus, String phoneNumber, Double sum,
			String username) {
		this.user = user;
		this.address = address;
		this.createtime = createtime;
		this.payStatus = payStatus;
		this.phoneNumber = phoneNumber;
		this.sum = sum;
		this.username = username;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createtime", length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	@ManyToMany
	public List<Food> getFoods() {
		return foods;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Column(name = "payStatus")
	public Integer getPayStatus() {
		return this.payStatus;
	}

	@Column(name = "phoneNumber", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	@Column(name = "sum", precision = 10)
	public double getSum() {
		return this.sum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid", nullable = false)
	public User getUser() {
		return this.user;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public void setFoods(List<Food> foods) {
		this.foods = foods;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public void setSum(Double sum) {
		this.sum = sum;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
