package com.model.takeout;
// Generated 2015-9-21 21:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.model.Model;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "takeout")
public class Region extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = 9214754358858042060L;
	private List<Region> children = new ArrayList<Region>();
	private int id;
	private String name;
	private Region parent;
	private String phoneNumber;
	private String postCode;
	private String type;

	public Region() {
	}

	public Region(int id, Region parent, String type) {
		this.id = id;
		this.parent = parent;
		this.type = type;
	}

	public Region(int id, Region parent, String name, String phoneNumber, String postCode, String type,
			List<Region> children) {
		this.id = id;
		this.parent = parent;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.postCode = postCode;
		this.type = type;
		this.children = children;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parent")
	public List<Region> getChildren() {
		return this.children;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentId", nullable = false)
	public Region getParent() {
		return this.parent;
	}

	@Column(name = "phoneNumber", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	@Column(name = "postCode", length = 20)
	public String getPostCode() {
		return this.postCode;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setChildren(List<Region> children) {
		this.children = children;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setParent(Region parent) {
		this.parent = parent;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public void setType(String type) {
		this.type = type;
	}

}
