package com.model.takeout;
// Generated 2015-9-18 16:25:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.model.Model;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "takeout")
public class User extends Model {

	/**
	 *
	 */
	private static final long serialVersionUID = 1914328405075429208L;
	private String address;
	private Integer id;
	private Boolean locked;
	private String name;
	private String password;
	private String phoneNumber;

	public User() {
	}

	public User(String password) {
		this.password = password;
	}

	public User(String name, String phoneNumber, String address, String password, Boolean locked) {
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.password = password;
		this.locked = locked;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "locked")
	public Boolean getLocked() {
		return this.locked;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	@Column(name = "phoneNumber", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

}
